version: "3.9"
services:
  app-backend-dev:
    image: app-backend
    container_name: ${COMPOSE_PROJECT_NAME:-app-backend}
    ports:
      - ${APP_BACKEND_PORT:-5000}:8080 # host:container
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://db/links-app
      - SPRING_R2DBC_USERNAME=links-app
      - SPRING_R2DBC_PASSWORD=links1
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://db/links-app
      - SPRING_LIQUIBASE_USER=links-app
      - SPRING_LIQUIBASE_PASSWORD=links1
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_LINKSLOGIN_CLIENTID=${OAUTH_CLIENTID}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_LINKSLOGIN_CLIENTSECRET=${OAUTH_CLIENTSECRET}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_LINKSLOGIN_REDIRECT_URI=${OAUTH_REDIRECT_URI:-http://localhost:5000/login/oauth2/code/linkslogin}
  db:
    image: 'postgres:14.1-alpine'
    container_name: db
    ports:
      - "15432:5432" # for access when developing
    environment:
      - POSTGRES_USER=links-app
      - POSTGRES_PASSWORD=links1